Do not do `truncate table` operation if not requested explicitly
scylladb/scylla-bench pull request #149
Opened 2024-10-17 10:49 UTC by vponomaryov

If it is needed to do truncation of the DB table, then just use following new parameter:

```
  -truncate-table
```

With this change it will be possible to use multiple scylla-bench concurrent commands which won't truncate each other's data.

Closes: https://github.com/scylladb/scylla-bench/issues/30
Closes: https://github.com/scylladb/scylla-bench/issues/130

2024-10-17 13:21 UTC, dkropachev commented
> > @vponomaryov , if you want to run them in validation mode it can work only by chance. If in regular mode, table won't be truncated.
> > To make it work in parallel on the same table we need somehow split targeted primary key values between runners.
> 
> Different concurrent commands use index offsets. So, data is not overlapped. And chance is 100% in this case.

`partition-offset` - works only for sequential workload

2024-10-17 16:51 UTC, dkropachev commented
> > > > @vponomaryov , if you want to run them in validation mode it can work only by chance. If in regular mode, table won't be truncated.
> > > > To make it work in parallel on the same table we need somehow split targeted primary key values between runners.
> > > 
> > > 
> > > Different concurrent commands use index offsets. So, data is not overlapped. And chance is 100% in this case.
> > 
> > 
> > `partition-offset` - works only for sequential workload
> 
> Changed the logic to consider the workload type.

What I meant is that if your purpose to run couple of `s-b` in parallel targeting same table, it should be solved in a such a way that would cover all the cases, not only sequential.

2024-10-18 15:37 UTC, vponomaryov commented
@dkropachev done

2024-10-20 08:06 UTC, fruch approved these changes
LGTM

2024-10-20 19:01 UTC, dkropachev requested changes
You also forgot about `RangeScan`,
It should go into `RangeOffset, `RangeCount`

I also would prefere different CLI, something like:
```
   --worker-id N
```
where `partitionOffset := (workerID - 1) * partitiionCount` and `truncateTable := workerID != 0`

2024-10-21 07:14 UTC, fruch commented
> You also forgot about `RangeScan`, It should go into `RangeOffset` and `RangeCount`
> 
> I also would prefere different CLI, something like:
> 
> ```
>    --worker-id N
> ```
> 
> where `partitionOffset := (workerID - 1) * partitiionCount` and `truncateTable := workerID != 0`

how worker ID is related to the question ?, user should be able to say, should the stress tool truncate or not, same as in c-s. I fail to see how this is related to the title of this PR.

2024-10-21 08:08 UTC, vponomaryov commented on pkg/workloads/workloads.go
> +	pkOffset := int64(threadId) + basicPkOffset
Why do you propose to summarize the partition "offset" with the partition "count"?
Both serve different goals.

2024-10-21 08:17 UTC, vponomaryov commented
> You also forgot about `RangeScan`, It should go into `RangeOffset` and `RangeCount`

I didn't forgot about "scan". It is explicitly mentioned to not support partition offsets.
Why? I am not aware about the use cases for it.

The main use case here is ability to disable truncation of a table with clear purpose - running multiple scylla-bench commands against single DB table for having cumulative "piopulation" effect and not cumulative "breaking" one.

> I also would prefere different CLI, something like:
> 
> ```
>    --worker-id N
> ```
> 
> where `partitionOffset := (workerID - 1) * partitiionCount` and `truncateTable := workerID != 0`

I have 2 concerns with this proposal:
1) Why should user count number of workers if he may avoid it? I don't see sense in it.
2) Truncation of a table should not be dependent on worker numbers at all. User decides whether he needs it or not, without relation to workers number.

2024-10-21 15:19 UTC, fruch commented
* lets split this one to it's two commit, and them test separately

2024-10-21 17:00 UTC, vponomaryov commented
> * lets split this one to it's two commit, and them test separately

Splitted the second commit to another PR here:
- https://github.com/scylladb/scylla-bench/pull/150

2024-10-21 20:47 UTC, dkropachev approved these changes
@vponomaryov , my assumption was that data validation won't work if `s-b` instances are writing to the same table, which is not the case, which changes a lot and now I am ok with your cli

2024-10-22 23:24 UTC, roydahan commented
seems like we can merge.

2024-10-23 08:09 UTC, merged