Work around gocql 1621
scylladb/scylla-bench pull request #97
Opened 2022-06-30 07:54 UTC by fruch

2022-09-01 07:47 UTC, vponomaryov requested changes
Please, leave only "keyspace" part of the change.
For full workability we will need the unreleased version of `gocql` with the following fix: https://github.com/scylladb/gocql/pull/104

2022-09-01 07:55 UTC, fruch commented
> Please, leave only "keyspace" part of the change. For full workability we will need the unreleased version of `gocql` with the following fix: [scylladb/gocql#104](https://github.com/scylladb/gocql/pull/104)

I'm not sure how  [scylladb/gocql#104](https://github.com/scylladb/gocql/pull/104) is related to should we advance the version or not, why wouldn't we ? 

if for testing specific fixes, we can build and test, i'm not following what do you mean here.

2022-09-01 08:19 UTC, vponomaryov commented
> > Please, leave only "keyspace" part of the change. For full workability we will need the unreleased version of `gocql` with the following fix: [scylladb/gocql#104](https://github.com/scylladb/gocql/pull/104)
> 
> I'm not sure how [scylladb/gocql#104](https://github.com/scylladb/gocql/pull/104) is related to should we advance the version or not, why wouldn't we ?
> 
> if for testing specific fixes, we can build and test, i'm not following what do you mean here.

At first, we will need the update for sure.
At second, such a change must be in a separate PR, because both existing commits are not dependant on each other.

2022-09-01 08:21 UTC, fruch commented
> > > Please, leave only "keyspace" part of the change. For full workability we will need the unreleased version of `gocql` with the following fix: [scylladb/gocql#104](https://github.com/scylladb/gocql/pull/104)
> > 
> > 
> > I'm not sure how [scylladb/gocql#104](https://github.com/scylladb/gocql/pull/104) is related to should we advance the version or not, why wouldn't we ?
> > if for testing specific fixes, we can build and test, i'm not following what do you mean here.
> 
> At first, we will need the update after merge of the mentioned issue - it is for sure. At second, such a change must be in a separate PR, because both existing commits are not dependant on each other.

do you have any evidence this specific issue, part of what holding the retries

2022-09-01 08:25 UTC, vponomaryov commented
> > > > Please, leave only "keyspace" part of the change. For full workability we will need the unreleased version of `gocql` with the following fix: [scylladb/gocql#104](https://github.com/scylladb/gocql/pull/104)
> > > 
> > > 
> > > I'm not sure how [scylladb/gocql#104](https://github.com/scylladb/gocql/pull/104) is related to should we advance the version or not, why wouldn't we ?
> > > if for testing specific fixes, we can build and test, i'm not following what do you mean here.
> > 
> > 
> > At first, we will need the update after merge of the mentioned issue - it is for sure. At second, such a change must be in a separate PR, because both existing commits are not dependant on each other.
> 
> do you have any evidence this specific issue, part of what holding the retries

https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/longevity-quorum-failure-reproducer-scylla-bench-small-partitions-3h/18/consoleFull

2022-09-01 08:37 UTC, vponomaryov approved these changes

2022-09-04 14:12 UTC, roydahan approved these changes

2022-09-04 14:12 UTC, merged